name: Python CI

on:
  push:
    branches:
        - main

permissions:
  contents: write

jobs:
    python-ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push the Docker Image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-hello:${{ github.run_number }} .
                docker push ${{ secrets.DOCKER_USERNAME }}/flask-hello:${{ github.run_number }}

            - name: Update Terraform Script
              run: |
                cd terraform
                sed -i "s|\(default\s*=\s*\"\)[^\"]\+\(\"\)|\1${{ secrets.DOCKER_USERNAME }}/flask-hello:${{ github.run_number }}\2|" variables.tf
                git config user.name "GitHub Actions"
                git config user.email "actions@github.com"
                git add variables.tf
                git commit -m "Update variables.tf"
                git push